/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Cars: typeof import('./src/components/partials/Cars.vue')['default']
    Dashboard: typeof import('./src/components/layout/Dashboard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    LayoutMain: typeof import('./src/components/layout/LayoutMain.vue')['default']
    PokemonDetails: typeof import('./src/components/PokemonDetails.vue')['default']
    POkemonDetails: typeof import('./src/components/POkemonDetails.vue')['default']
    PokemonDisplay: typeof import('./src/components/PokemonDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/partials/SideBar.vue')['default']
  }
}
